export enum PortafolioFieldType {
  DATE = 'DATE',
  DATE_RANGE = 'DATE_RANGE',
  TEXT = 'TEXT',
  NUMERIC = 'NUMERIC',
  TOGGLE = 'TOGGLE',
  SELECTOR_UNIQUE = 'SELECTOR_UNIQUE',
  AUTOCOMPLETE_SELECTOR = 'AUTOCOMPLETE_SELECTOR'
}