/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://lbnvb7ymdffbxd6nswqdxl46ly.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-dzrzljqzk5dldeaghnuwinawju",
    "aws_cognito_identity_pool_id": "us-east-1:e99a7878-6ee7-431e-b1fc-c686e1be08d2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SfSa1dMOh",
    "aws_user_pools_web_client_id": "2pj0hu19vakpb501mrbo3um8vp",
    "oauth": {
        "domain": "mypo11c19568-11c19568-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.d9y58zm1bjgsd.amplifyapp.com/,http://localhost:3000/",
        "redirectSignOut": "https://dev.d9y58zm1bjgsd.amplifyapp.com/,http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
